#!/bin/sh
set -e
go build -o docker/app github.com/syzoj/syzoj-ng-go/svc/main/app
go build -o docker/migrate github.com/syzoj/syzoj-ng-go/svc/main/migrate
docker build docker -t syzoj/syzoj-ng
docker build docker-build -t syzoj/syzoj:ng
