version: '3'
services:
  minio:
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      - "MINIO_ACCESS_KEY=KrF5OgAHvZtqtbhQ"
      - "MINIO_SECRET_KEY=rTg0TZlYI2H0Br0SJrpwgPQtii8hsyRl"
    networks:
      - syzojng
    command: ["server", "/data"]
  mysql:
    image: mariadb:10.3
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - syzojng
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
  redis:
    image: redis
    networks:
      - syzojng
    volumes:
      - redis-data:/var/lib/redis
    command: ["redis-server", "--appendonly", "yes"]
  redis-cache:
    image: redis
    networks:
      - syzojng
    command: ["redis-server", "--appendonly", "yes"]
  rabbitmq:
    image: rabbitmq
    networks:
     -  syzojng
  app:
    image: syzoj/syzoj-ng
    networks:
      - syzojng
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=syzoj
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=syzoj
      - REDIS_ADDR=redis:6379
      - CACHE_REDIS_ADDR=redis-cache:6379
      - HTTP_LISTEN_ADDR=0.0.0.0:5283
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=KrF5OgAHvZtqtbhQ
      - S3_SECRET_KEY=rTg0TZlYI2H0Br0SJrpwgPQtii8hsyRl
      - JUDGE_TOKEN=123456
    command: ["/app/app"]
  syzoj:
    image: syzoj/syzoj:ng
    networks:
      - syzojng
    volumes:
      - ./config:/opt/config
      - ./data/syzoj:/opt/syzoj/data
    command: ["node", "/opt/syzoj/app.js", "-c", "/opt/config/web.json"]
    working_dir: "/opt/syzoj"
  judger:
    image: syzoj/syzoj:ng
    networks:
      - syzojng
    volumes:
      - ./config:/opt/config
      - syzoj-data:/opt/syzoj/data
    working_dir: "/opt/judge-v3"
    command: ["node", "/opt/judge-v3/lib/daemon/index.js", "-c", "/opt/config/daemon.json", "-v"]
    stop_signal: SIGKILL
  runner:
    image: syzoj/syzoj:base
    networks:
      - syzojng
    volumes:
      - ./config:/opt/config
      - syzoj-data:/opt/syzoj/data
      - ./sandbox-rootfs:/sandbox-rootfs
      - ./data/bin:/opt/binary
      - ./data/temp1:/opt/temp
    working_dir: "/opt/judge-v3"
    command: ["node", "/opt/judge-v3/lib/runner/index.js", "-s", "/opt/config/runner-shared.json", "-i", "/opt/config/runner-instance.json", "-v"]
    privileged: true
  nginx:
    image: nginx
    networks:
      - syzojng
    volumes:
      - ./config/nginx:/etc/nginx:ro
    ports:
      - 5283:5283
networks:
  syzojng:
volumes:
  mysql-data:
  minio:
  redis-data:
  syzoj-data:
