version: '2.2'
services:
  es01:
    build: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms192m -Xmx192m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/ssd/syzoj-ng/esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - syzojnet
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /mnt/ssd/syzoj-ng/mysql:/var/lib/mysql
    networks:
      - syzojnet
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
  redis-session:
    image: redis
    volumes:
      - /mnt/ssd/syzoj-ng/redis:/data
    networks:
      - syzojnet
    entrypoint: ['redis-server', '--appendonly', 'yes']
  redis-cache:
    image: redis
    networks:
      - syzojnet
  automation:
    build:
      context: ../node/automation
      dockerfile: $PWD/automation/Dockerfile
    environment:
      USER_MYSQL_HOST: mysql
      USER_MYSQL_USER: user
      USER_MYSQL_PASSWORD: 123456
      USER_MYSQL_DATABASE: user
      PROBLEM_MYSQL_HOST: mysql
      PROBLEM_MYSQL_USER: problem
      PROBLEM_MYSQL_PASSWORD: 123456
      PROBLEM_MYSQL_DATABASE: problem
      PROBLEM_DATA_HTTP_URL: http://problem-data:3302
      CACHE_REDIS_HOST: redis-cache
      HTTP_LISTEN_PORT: 3300
      PROBLEM_ELASTICSEARCH: http://es01:9200
    networks:
      - syzojnet
  interface:
    build: interface
    environment:
      AUTOMATION_HTTP_URL: http://automation:3300
      USER_MYSQL_HOST: mysql
      USER_MYSQL_USER: user
      USER_MYSQL_PASSWORD: 123456
      USER_MYSQL_DATABASE: user
      PROBLEM_MYSQL_HOST: mysql
      PROBLEM_MYSQL_USER: problem
      PROBLEM_MYSQL_PASSWORD: 123456
      PROBLEM_MYSQL_DATABASE: problem
      SESSION_REDIS_ADDR: redis-session:6379
      CACHE_REDIS_ADDR: redis-cache:6379
      HTTP_LISTEN_PORT: 3301
    networks:
      - syzojnet
  problem-data:
    build: problem-data
    environment:
      AUTOMATION_HTTP_URL: http://automation:3300
      DATA_PATH: /data
      HTTP_LISTEN_PORT: 3302
    volumes:
      - /mnt/ssd/syzoj-ng/problem-data:/data
    networks:
      - syzojnet
  install:
    build: install
    environment:
      PROBLEM_MYSQL_ADDR: mysql
      ELASTIC_ADDR: "http://es01:9200"
    networks:
      - syzojnet

networks:
  syzojnet:
