tags:
  cache/user/*/self/request:
  cache/user/*/self/loaded:
  cache/problem/*/info/request:
  cache/problem/*/info/loaded:
  cache/problem/*/summary/request:
  cache/problem/*/summary/loaded:
  cache/problem-data/*/info/request:
  cache/problem-data/*/info/loaded:
  user/*/register:
  problem-data/*/delete:
  problem-data/*/upload-data:
  problem-data/*/extract:
tasks:
  - script: cache/user_self
    tags:
      - cache/user/*/self/request
      - user/*/register
  - script: problem_upload-data_extract
    tags:
      - problem-data/*/upload-data
  - script: cache/problem_info
    tags:
      - cache/problem/*/info/request
  - script: cache/problem_summary
    tags:
      - cache/problem/*/summary/request
  - script: cache/problem_data_info
    tags:
      - problem-data/*/extract
      - cache/problem-data/*/info/request
  - script: problem_elasticsearch
    tags:
      - cache/problem/*/info/loaded
